### ISSUE TITLE
no support gpg2

### ISSUE THREAD

**Issue by crimsen** [crimsen/PasswordSafe#15]
implement in gnupg.GPG homepath, binary and keyring

**Comment by groegert** [comment]
gpg2 is generally supported, but
on 2016-06-16 with GPG 2.1.13 the new status 'KEY_CONSIDERED' was introduced. This new status is not supported by python-gnupg <= 0.38
see https://bitbucket.org/vinay.sajip/python-gnupg/issues/55/add-support-for-gnupg-2113s-key_considered for a patch of python-gnupg
