### ISSUE TITLE
History and date of creation in PasswordObjects

### ISSUE THREAD

**Issue by groegert** [crimsen/PasswordSafe#7]
Would be great to have something like a history and a date when the password was created in the password objects.
With a date a user can check when the password was changed last time. This would help in changing passwords periodically as it is proposed by security rules.
With a history also historical protected data can be accessed. I.e. you do have an GPG-encrypted file. For any reason you need to revoke that GPG-key and need to create a new one. To decrypt the file you will need the old key and the _old password_.

**Comment by crimsen** [comment]
added in version 1.3.2
